require_relative('../models/city')
require_relative('../models/country')
require_relative('../models/trip')
require ('pry')

country1 = Country.new({'name' => 'Scotland'})
country2 = Country.new({'name' => 'England'})
country3 = Country.new({'name' => 'Wales'})
country4 = Country.new({'name' => 'Ireland'})
country5 = Country.new({'name' => 'Northern Ireland'})
country6 = Country.new({'name' => 'France'})
country7 = Country.new({'name' => 'Brazil'})
country8 = Country.new({'name' => 'Italty'})
country9 = Country.new({'name' => 'Mexico'})
country10 = Country.new({'name' => 'USA'})
country11 = Country.new({'name' => 'Germany'})
country12 = Country.new({'name' => 'Japan'})
country13 = Country.new({'name' => 'Russia'})
country14 = Country.new({'name' => 'Nepal'})
country15 = Country.new({'name' => 'Poland'})

country1.save()
country2.save()
country3.save()
country4.save()
country5.save()
country6.save()
country7.save()
country8.save()
country9.save()
country10.save()
country11.save()
country12.save()
country13.save()
country14.save()
country15.save()

city1 = City.new({'country_id' => country1.id, 'name' => 'Edinburgh'})
city2 = City.new({'country_id' => country1.id, 'name' => 'Perth'})
city3 = City.new({'country_id' => country2.id, 'name' => 'London'})
city4 = City.new({'country_id' => country2.id, 'name' => 'Brighton'})
city5 = City.new({'country_id' => country6.id, 'name' => 'Paris'})
city6 = City.new({'country_id' => country6.id, 'name' => 'Lyon'})
city7 = City.new({'country_id' => country10.id, 'name' => 'New York'})
city8 = City.new({'country_id' => country10.id, 'name' => 'Portland'})
city9 = City.new({'country_id' => country13.id, 'name' => 'Saint Petersburg'})
city10 = City.new({'country_id' => country13.id, 'name' => 'Moscow'})

city1.save()
city2.save()
city3.save()
city4.save()
city5.save()
city6.save()
city7.save()
city8.save()
city9.save()
city10.save()

seed1 = Seed.new({'country_id' => country1.id, 'city_id' => city1.id, 'visited' => 'visited'})
seed2 = Seed.new({'country_id' => country1.id, 'city_id' => city2.id, 'visited' => 'visited'})
seed3 = Seed.new({'country_id' => country2.id, 'city_id' => city3.id, 'visited' => 'visited'})
seed4 = Seed.new({'country_id' => country2.id, 'city_id' => city4.id, 'visited' => 'not visited'})
seed5 = Seed.new({'country_id' => country6.id, 'city_id' => city5.id, 'visited' => 'visited'})
seed6 = Seed.new({'country_id' => country6.id, 'city_id' => city6.id, 'visited' => 'not visited'})
seed7 = Seed.new({'country_id' => country10.id, 'city_id' => city7.id, 'visited' => 'visited'})
seed8 = Seed.new({'country_id' => country10.id, 'city_id' => city8.id, 'visited' => 'not visited'})
seed9 = Seed.new({'country_id' => country13.id, 'city_id' => city9.id, 'visited' => 'not visited'})
seed10 = Seed.new({'country_id' => country13.id, 'city_id' => city10.id, 'visited' => 'not visited'})

seed1.save()
seed2.save()
seed3.save()
seed4.save()
seed5.save()
seed6.save()
seed7.save()
seed8.save()
seed9.save()
seed10.save()

binding.pry
nil
