require_relative('../models/city')
require_relative('../models/country')
require_relative('../models/trip')
require ('pry')

country1 = Country.new({'name' => 'Scotland'})
country2 = Country.new({'name' => 'England'})
country3 = Country.new({'name' => 'Wales'})
country4 = Country.new({'name' => 'Ireland'})
country5 = Country.new({'name' => 'Northern Ireland'})
country6 = Country.new({'name' => 'France'})
country7 = Country.new({'name' => 'Brazil'})
country8 = Country.new({'name' => 'Italty'})
country9 = Country.new({'name' => 'Mexico'})
country10 = Country.new({'name' => 'USA'})
country11 = Country.new({'name' => 'Germany'})
country12 = Country.new({'name' => 'Japan'})
country13 = Country.new({'name' => 'Russia'})
country14 = Country.new({'name' => 'Nepal'})
country15 = Country.new({'name' => 'Poland'})

country1.save()
country2.save()
country3.save()
country4.save()
country5.save()
country6.save()
country7.save()
country8.save()
country9.save()
country10.save()
country11.save()
country12.save()
country13.save()
country14.save()
country15.save()


binding.pry
nil
